### ISSUE TITLE
about pretrain weights

### ISSUE THREAD

**Issue by MIaomiao426** [francescotonini/multimodal-across-domains-gaze-target-detection#3]
It's a great job! I'd like to know how the init_weights.pt is generated?
Now I am training my own model, but I don't know how to generate initial weights similar to yours TT
Could u provide some details about it？

**Comment by francescotonini** [comment]
Hi, the `init_weights.pt` are the ones of [Chong et al.](https://github.com/ejcgt/attention-target-detection) plus weights of the depth branch obtained by training a ResNet50 for scene classification using pseudo-labeled depth maps from Places205.
